[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"
